repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: bash -c 'cd scheduler && make lint'
        language: system
        pass_filenames: false
        always_run: true

      - id: typecheck
        name: typecheck
        entry: bash -c 'cd scheduler && make typecheck'
        language: system
        pass_filenames: false
        always_run: true

      - id: test
        name: test
        entry: bash -c 'cd scheduler && make test'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
