x-base: &base
  env_file: .env
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "5m"
      max-file: "2"

services:
  tailscale:
    <<: *base
    image: tailscale/tailscale:v1.98.3
    container_name: tailscale
    hostname: homelab
    volumes:
      - ./ts-data:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW

  vaultwarden:
    <<: *base
    image: vaultwarden/server:1.36.0
    container_name: vaultwarden
    network_mode: "service:tailscale"
    volumes:
      - ./vw-data:/data
    depends_on:
      - tailscale

  scheduler:
    <<: *base
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    container_name: scheduler
    volumes:
      - ./vw-data:/data:ro
      - ./backups:/app/backups
    depends_on:
      - vaultwarden
