name: CI

on:
  pull_request:

jobs:
  scheduler:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scheduler

    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv sync --frozen

      - name: Lint
        run: |
          uv run --frozen ruff format --check
          uv run --frozen ruff check

      - name: Typecheck
        run: uv run --frozen mypy .

      - name: Test
        run: uv run --frozen pytest -s -vv --cov=src --cov-report=term-missing tests
